"""Multi-tenant apply entrypoint.

`apply_for_user(user_id, application_id)` is the worker-facing function. It:

  1. Claims the application atomically (status -> 'in_progress').
  2. Opens an apply_attempts row.
  3. Loads the per-user profile, tailored resume + PDF, and the job row.
  4. Calls into the existing tool-use loop (`runner.run_apply`).
  5. Records cost + usage + final attempt state, releases the application.

All persistence happens through `applyd.db` repos using the service-role
client (RLS bypass). Every step is best-effort idempotent so a crashed
worker leaves a `failed` row instead of a stuck `in_progress` one.
"""

from __future__ import annotations

import json
import logging
import os
import tempfile
from pathlib import Path
from typing import Any

from ..config import load_env
from ..db import (
    ApplicationsRepo,
    ApplyAttemptsRepo,
    JobsRepo,
    TailoredResumesRepo,
    UsageEventsRepo,
    UserProfilesRepo,
    cost_cents_for_apply,
    get_client,
)
from .runner import DEFAULT_MODEL, run_apply

logger = logging.getLogger("applyd.apply.saas")

CLAIMABLE_FROM: tuple[str, ...] = ("tailored", "failed")


def _profile_to_prose(profile: dict[str, Any]) -> str:
    """Fallback prose blob when `profile_answers` is null.

    The agent expects a single free-form text. We synthesize a minimal but
    truthful sketch from the structured columns so the apply doesn't die for
    lack of a hand-written narrative.
    """
    parts: list[str] = ["# applyd profile (autogenerated stub)\n"]
    if name := profile.get("full_name"):
        parts.append(f"- Full legal name: {name}")
    if phone := profile.get("phone"):
        parts.append(f"- Phone: {phone}")
    if linkedin := profile.get("linkedin_url"):
        parts.append(f"- LinkedIn: {linkedin}")
    if github := profile.get("github_url"):
        parts.append(f"- GitHub: {github}")
    if portfolio := profile.get("portfolio_url"):
        parts.append(f"- Portfolio: {portfolio}")
    if auth := profile.get("work_auth_summary"):
        parts.append(f"\n## Work authorization\n{auth}")
    if sponsor := profile.get("sponsorship_needed_countries"):
        parts.append(f"\nSponsorship required for: {', '.join(sponsor)}")
    if strategy := profile.get("strategy"):
        parts.append(f"\n## Strategy\n{strategy}")
    if not any(profile.get(k) for k in ("full_name", "phone", "linkedin_url")):
        parts.append("(Profile is empty — agent should skip the job if any required field is unanswerable.)")
    return "\n".join(parts)


def _build_profile_text(profile: dict[str, Any] | None) -> str:
    if not profile:
        return "(Profile missing — agent should skip the job for any required free-text field.)"
    answers = profile.get("profile_answers")
    if isinstance(answers, str) and answers.strip():
        return answers
    return _profile_to_prose(profile)


def apply_for_user(user_id: str, application_id: str) -> dict[str, Any]:
    """Run one apply for one user. Handles claim/release/attempt/usage internally.

    Returns a dict: {status, application_id, attempt_id, cost_cents, tokens, ...}.
    `status='lost_race'` means another worker claimed the row first.
    """
    load_env()
    sb = get_client()
    apps = ApplicationsRepo(sb)
    attempts = ApplyAttemptsRepo(sb)
    jobs = JobsRepo(sb)
    profiles = UserProfilesRepo(sb)
    tailored = TailoredResumesRepo(sb)
    usage = UsageEventsRepo(sb)

    # 1. application exists?
    application = apps.get(application_id)
    if application is None:
        raise ValueError(f"application {application_id!r} not found")

    # 2. claim atomically.
    claimed = apps.claim(application_id, from_statuses=CLAIMABLE_FROM)
    if claimed is None:
        logger.info("[apply] lost race on %s", application_id)
        return {"status": "lost_race", "application_id": application_id}

    # 3. open the attempt.
    attempt = attempts.insert(
        application_id=application_id,
        user_id=user_id,
        status="pending",
    )
    attempt_id: str = attempt["id"]

    job_id: str = claimed["job_id"]
    tmp_pdf_path: str | None = None
    model = os.environ.get("APPLYD_APPLY_MODEL", DEFAULT_MODEL)
    test_mode = os.environ.get("APPLYD_TEST_MODE", "true").lower() == "true"

    def _finish(
        status: str,
        reason: str | None,
        tokens: dict[str, int] | None = None,
        browser_mb: float = 0.0,
        turn_count: int | None = None,
        tool_call_counts: dict[str, int] | None = None,
    ) -> dict[str, Any]:
        tokens = tokens or {"input": 0, "output": 0, "cache_read": 0, "cache_write": 0}
        prompt = tokens.get("input", 0)
        completion = tokens.get("output", 0)
        cached = tokens.get("cache_read", 0)

        try:
            cost_cents = cost_cents_for_apply(
                model=model,
                prompt_tokens=prompt,
                completion_tokens=completion,
                cached_tokens=cached,
                browser_mb=browser_mb,
            )
        except ValueError:
            # Unknown model in pricing table — log but don't blow up the apply.
            logger.exception("[apply] unknown model in pricing: %s", model)
            cost_cents = 0

        attempts.end(
            attempt_id,
            status=status,
            reason=reason,
            prompt_tokens=prompt,
            completion_tokens=completion,
            turn_count=turn_count,
            tool_call_counts=tool_call_counts,
        )
        usage.record(
            user_id=user_id,
            event_type="apply",
            cost_cents=cost_cents,
            metadata={
                "model": model,
                "prompt_tokens": prompt,
                "completion_tokens": completion,
                "cached_tokens": cached,
                "browser_mb": browser_mb,
                "test_mode": test_mode,
                "attempt_id": attempt_id,
                "application_id": application_id,
                "reason": reason,
            },
        )
        apps.release(application_id, status=status, reason=reason)
        return {
            "status": status,
            "application_id": application_id,
            "attempt_id": attempt_id,
            "cost_cents": cost_cents,
            "tokens": tokens,
            "reason": reason,
        }

    try:
        # 4. job row.
        job = jobs.get(job_id)
        if job is None or not getattr(job, "active", True):
            return _finish("skipped", "job_missing_or_inactive")

        # 5. profile (best-effort — never block the apply for lack of it).
        profile = profiles.get(user_id)
        profile_md = _build_profile_text(profile)

        # 6. tailored resume + PDF.
        tailored_row = tailored.get(user_id, job_id)
        if tailored_row is None:
            return _finish("failed", "no_tailored_resume")

        pdf_storage_path: str | None = tailored_row.get("pdf_storage_path")
        if not pdf_storage_path:
            return _finish("failed", "no_tailored_pdf")

        try:
            pdf_bytes = sb.storage.from_("resumes").download(pdf_storage_path)
        except Exception as exc:  # noqa: BLE001
            return _finish("failed", f"pdf_download_failed: {type(exc).__name__}: {exc}")

        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as fp:
            fp.write(pdf_bytes)
            tmp_pdf_path = fp.name

        resume_tex = tailored_row.get("latex_source") or ""
        tailor_metadata = tailored_row.get("tailor_metadata") or {}
        try:
            metadata_json = json.dumps(tailor_metadata)
        except (TypeError, ValueError):
            metadata_json = "{}"

        # 7. drive the tool-use loop.
        result = run_apply(
            job_id=job.id,
            company=job.company,
            title=job.title,
            job_url=job.url,
            resume_pdf_path=tmp_pdf_path,
            profile_md=profile_md,
            resume_tex=resume_tex,
            tailor_metadata_json=metadata_json,
            model=model,
            test_mode=test_mode,
        )

        status_raw = result.get("status", "failed")
        # The runner emits a couple of values not in our terminal set ("lost_race"
        # never originates here; "gated:*" notes come back on `status='skipped'`).
        status = status_raw if status_raw in {"applied", "skipped", "failed"} else "failed"
        note = result.get("note") or None
        return _finish(
            status,
            note,
            tokens=result.get("tokens"),
            browser_mb=float(result.get("browser_mb", 1.5)),
            turn_count=result.get("turn_count"),
            tool_call_counts=result.get("tool_call_counts") or None,
        )

    except Exception as exc:  # noqa: BLE001
        logger.exception("[apply] crashed for app %s: %s", application_id, exc)
        return _finish("failed", f"runner_crash: {type(exc).__name__}: {exc}")
    finally:
        if tmp_pdf_path:
            try:
                Path(tmp_pdf_path).unlink(missing_ok=True)
            except OSError:
                logger.warning("[apply] failed to clean up %s", tmp_pdf_path)
